import IconAbnormal from 'terra-icon/lib/icon/IconAbnormal';
import IconAbnormalLowLight from 'terra-icon/lib/icon/IconAbnormalLowLight';
import IconAdd from 'terra-icon/lib/icon/IconAdd';
import IconAddPerson from 'terra-icon/lib/icon/IconAddPerson';
import IconAlert from 'terra-icon/lib/icon/IconAlert';
import IconAlertLowLight from 'terra-icon/lib/icon/IconAlertLowLight';
import IconAllergy from 'terra-icon/lib/icon/IconAllergy';
import IconAnalytics from 'terra-icon/lib/icon/IconAnalytics';
import IconAnnouncement from 'terra-icon/lib/icon/IconAnnouncement';
import IconArchive from 'terra-icon/lib/icon/IconArchive';
import IconAttachment from 'terra-icon/lib/icon/IconAttachment';
import IconAudio from 'terra-icon/lib/icon/IconAudio';
import IconAutoText from 'terra-icon/lib/icon/IconAutoText';
import IconAvailable from 'terra-icon/lib/icon/IconAvailable';
import IconAway from 'terra-icon/lib/icon/IconAway';

import IconBedAssigned from 'terra-icon/lib/icon/IconBedAssigned';
import IconBedAssignedLowLight from 'terra-icon/lib/icon/IconBedAssignedLowLight';
import IconBedRequested from 'terra-icon/lib/icon/IconBedRequested';
import IconBluetooth from 'terra-icon/lib/icon/IconBluetooth';
import IconBluetoothSlash from 'terra-icon/lib/icon/IconBluetoothSlash';
import IconBookmark from 'terra-icon/lib/icon/IconBookmark';
import IconBriefcase from 'terra-icon/lib/icon/IconBriefcase';
import IconBrokenImage from 'terra-icon/lib/icon/IconBrokenImage';
import IconBrokenLinkUnlink from 'terra-icon/lib/icon/IconBrokenLinkUnlink';
import IconBusy from 'terra-icon/lib/icon/IconBusy';

import IconCalculator from 'terra-icon/lib/icon/IconCalculator';
import IconCalendar from 'terra-icon/lib/icon/IconCalendar';
import IconCamera from 'terra-icon/lib/icon/IconCamera';
import IconCancel from 'terra-icon/lib/icon/IconCancel';
import IconCaretDown from 'terra-icon/lib/icon/IconCaretDown';
import IconCaretLeft from 'terra-icon/lib/icon/IconCaretLeft';
import IconCaretRight from 'terra-icon/lib/icon/IconCaretRight';
import IconCaretUp from 'terra-icon/lib/icon/IconCaretUp';
import IconCatalogueNumber from 'terra-icon/lib/icon/IconCatalogueNumber';
import IconCaution from 'terra-icon/lib/icon/IconCaution';
import IconCeMarking from 'terra-icon/lib/icon/IconCeMarking';
import IconChecklist from 'terra-icon/lib/icon/IconChecklist';
import IconCheckmark from 'terra-icon/lib/icon/IconCheckmark';
import IconChevron from 'terra-icon/lib/icon/IconChevron';
import IconChevronDown from 'terra-icon/lib/icon/IconChevronDown';
import IconChevronLeft from 'terra-icon/lib/icon/IconChevronLeft';
import IconChevronRight from 'terra-icon/lib/icon/IconChevronRight';
import IconChevronUp from 'terra-icon/lib/icon/IconChevronUp';
import IconCircleLinesSymbol from 'terra-icon/lib/icon/IconCircleLinesSymbol';
import IconCircleSymbol from 'terra-icon/lib/icon/IconCircleSymbol';
import IconCircleSymbolLight from 'terra-icon/lib/icon/IconCircleSymbolLight';
import IconClear from 'terra-icon/lib/icon/IconClear';
import IconClipboard from 'terra-icon/lib/icon/IconClipboard';
import IconClock from 'terra-icon/lib/icon/IconClock';
import IconClose from 'terra-icon/lib/icon/IconClose';
import IconCollapseRow from 'terra-icon/lib/icon/IconCollapseRow';
import IconComment from 'terra-icon/lib/icon/IconComment';
import IconCommit from 'terra-icon/lib/icon/IconCommit';
import IconComplete from 'terra-icon/lib/icon/IconComplete';
import IconCompose from 'terra-icon/lib/icon/IconCompose';
import IconConfidential from 'terra-icon/lib/icon/IconConfidential';
import IconConsultInstructionsForUse from 'terra-icon/lib/icon/IconConsultInstructionsForUse';
import IconCritical from 'terra-icon/lib/icon/IconCritical';
import IconCriticalLowLight from 'terra-icon/lib/icon/IconCriticalLowLight';
import IconCriticalInverse from 'terra-icon/lib/icon/IconCriticalInverse';
import IconCriticalInverseLowLight from 'terra-icon/lib/icon/IconCriticalInverseLowLight';

import IconDateOfManufacture from 'terra-icon/lib/icon/IconDateOfManufacture';
import IconDevice from 'terra-icon/lib/icon/IconDevice';
import IconDeviceAlert from 'terra-icon/lib/icon/IconDeviceAlert';
import IconDeviceAlertLowLight from 'terra-icon/lib/icon/IconDeviceAlertLowLight';
import IconDeviceCheck from 'terra-icon/lib/icon/IconDeviceCheck';
import IconDeviceCheckLowLight from 'terra-icon/lib/icon/IconDeviceCheckLowLight';
import IconDiamond from 'terra-icon/lib/icon/IconDiamond';
import IconDiamondLowLight from 'terra-icon/lib/icon/IconDiamondLowLight';
import IconDiamondSymbol from 'terra-icon/lib/icon/IconDiamondSymbol';
import IconDiamondSymbolLight from 'terra-icon/lib/icon/IconDiamondSymbolLight';
import IconDischargeComingDue from 'terra-icon/lib/icon/IconDischargeComingDue';
import IconDischargeComingDueLowLight from 'terra-icon/lib/icon/IconDischargeComingDueLowLight';
import IconDischargeComplete from 'terra-icon/lib/icon/IconDischargeComplete';
import IconDischargeCompleteLowLight from 'terra-icon/lib/icon/IconDischargeCompleteLowLight';
import IconDischargeOverDue from 'terra-icon/lib/icon/IconDischargeOverDue';
import IconDischargeOverDueLowLight from 'terra-icon/lib/icon/IconDischargeOverDueLowLight';
import IconDocumentPlus from 'terra-icon/lib/icon/IconDocumentPlus';
import IconDocuments from 'terra-icon/lib/icon/IconDocuments';
import IconDoNotDisturb from 'terra-icon/lib/icon/IconDoNotDisturb';
import IconDoorOpen from 'terra-icon/lib/icon/IconDoorOpen';
import IconDoubleChevronLeft from 'terra-icon/lib/icon/IconDoubleChevronLeft';
import IconDoubleChevronRight from 'terra-icon/lib/icon/IconDoubleChevronRight';
import IconDown from 'terra-icon/lib/icon/IconDown';
import IconDownload from 'terra-icon/lib/icon/IconDownload';
import IconDrugDrug from 'terra-icon/lib/icon/IconDrugDrug';
import IconDrugDrugLowLight from 'terra-icon/lib/icon/IconDrugDrugLowLight';
import IconDue from 'terra-icon/lib/icon/IconDue';
import IconDueSoon from 'terra-icon/lib/icon/IconDueSoon';
import IconDueSoonLowLight from 'terra-icon/lib/icon/IconDueSoonLowLight';

import IconEcRep from 'terra-icon/lib/icon/IconEcRep';
import IconEdit from 'terra-icon/lib/icon/IconEdit';
import IconEllipses from 'terra-icon/lib/icon/IconEllipses';
import IconEnvelope from 'terra-icon/lib/icon/IconEnvelope';
import IconEnvelopeFill from 'terra-icon/lib/icon/IconEnvelopeFill';
import IconError from 'terra-icon/lib/icon/IconError';
import IconErrorLowLight from 'terra-icon/lib/icon/IconErrorLowLight';
import IconErrorDark from 'terra-icon/lib/icon/IconErrorDark';
import IconExclamation from 'terra-icon/lib/icon/IconExclamation';
import IconExpandLess from 'terra-icon/lib/icon/IconExpandLess';
import IconExpandMore from 'terra-icon/lib/icon/IconExpandMore';
import IconExpandRow from 'terra-icon/lib/icon/IconExpandRow';
import IconExtensions from 'terra-icon/lib/icon/IconExtensions';
import IconExternalLink from 'terra-icon/lib/icon/IconExternalLink';

import IconFeatured from 'terra-icon/lib/icon/IconFeatured';
import IconFeaturedOff from 'terra-icon/lib/icon/IconFeaturedOff';
import IconFeaturedOutline from 'terra-icon/lib/icon/IconFeaturedOutline';
import IconFeaturedOutlineYellow from 'terra-icon/lib/icon/IconFeaturedOutlineYellow';
import IconFirst from 'terra-icon/lib/icon/IconFirst';
import IconFitHeight from 'terra-icon/lib/icon/IconFitHeight';
import IconFitScale from 'terra-icon/lib/icon/IconFitScale';
import IconFitWidth from 'terra-icon/lib/icon/IconFitWidth';
import IconFlag from 'terra-icon/lib/icon/IconFlag';
import IconFlipHorizontal from 'terra-icon/lib/icon/IconFlipHorizontal';
import IconFlipVertical from 'terra-icon/lib/icon/IconFlipVertical';
import IconFlowsheet from 'terra-icon/lib/icon/IconFlowsheet';
import IconFolder from 'terra-icon/lib/icon/IconFolder';
import IconForward from 'terra-icon/lib/icon/IconForward';
import IconFunnel from 'terra-icon/lib/icon/IconFunnel';

import IconGapChecking from 'terra-icon/lib/icon/IconGapChecking';
import IconGlasses from 'terra-icon/lib/icon/IconGlasses';
import IconGroup from 'terra-icon/lib/icon/IconGroup';

import IconHalfRating from 'terra-icon/lib/icon/IconHalfRating';
import IconHazardLow from 'terra-icon/lib/icon/IconHazardLow';
import IconHelp from 'terra-icon/lib/icon/IconHelp';
import IconHelpLowLight from 'terra-icon/lib/icon/IconHelpLowLight';
import IconHelpInverse from 'terra-icon/lib/icon/IconHelpInverse';
import IconHelpInverseLowLight from 'terra-icon/lib/icon/IconHelpInverseLowLight';
import IconHide from 'terra-icon/lib/icon/IconHide';
import IconHigh from 'terra-icon/lib/icon/IconHigh';
import IconHighLowLight from 'terra-icon/lib/icon/IconHighLowLight';
import IconHighInverse from 'terra-icon/lib/icon/IconHighInverse';
import IconHighInverseLowLight from 'terra-icon/lib/icon/IconHighInverseLowLight';
import IconHighPriority from 'terra-icon/lib/icon/IconHighPriority';
import IconHold from 'terra-icon/lib/icon/IconHold';
import IconHospital from 'terra-icon/lib/icon/IconHospital';
import IconHouse from 'terra-icon/lib/icon/IconHouse';

import IconImage from 'terra-icon/lib/icon/IconImage';
import IconImplant from 'terra-icon/lib/icon/IconImplant';
import IconIncomingCall from 'terra-icon/lib/icon/IconIncomingCall';
import IconIncomplete from 'terra-icon/lib/icon/IconIncomplete';
import IconIncompleteInverse from 'terra-icon/lib/icon/IconIncompleteInverse';
import IconIncompleteInverseLowLight from 'terra-icon/lib/icon/IconIncompleteInverseLowLight';
import IconInformation from 'terra-icon/lib/icon/IconInformation';
import IconInformationLowLight from 'terra-icon/lib/icon/IconInformationLowLight';
import IconInformationInverse from 'terra-icon/lib/icon/IconInformationInverse';
import IconInformationInverseLowLight from 'terra-icon/lib/icon/IconInformationInverseLowLight';
import IconIPass from 'terra-icon/lib/icon/IconIPass';
import IconItalicI from 'terra-icon/lib/icon/IconItalicI';

import IconKeyboard from 'terra-icon/lib/icon/IconKeyboard';
import IconKnurling from 'terra-icon/lib/icon/IconKnurling';

import IconLast from 'terra-icon/lib/icon/IconLast';
import IconLeft from 'terra-icon/lib/icon/IconLeft';
import IconLeftPane from 'terra-icon/lib/icon/IconLeftPane';
import IconLightbulb from 'terra-icon/lib/icon/IconLightbulb';
import IconLink from 'terra-icon/lib/icon/IconLink';
import IconList from 'terra-icon/lib/icon/IconList';
import IconLocationPin from 'terra-icon/lib/icon/IconLocationPin';
import IconLookback from 'terra-icon/lib/icon/IconLookback';
import IconLow from 'terra-icon/lib/icon/IconLow';
import IconLowLowLight from 'terra-icon/lib/icon/IconLowLowLight';
import IconLowRisk from 'terra-icon/lib/icon/IconLowRisk';
import IconLowRiskLowLight from 'terra-icon/lib/icon/IconLowRiskLowLight';

import IconManufacturer from 'terra-icon/lib/icon/IconManufacturer';
import IconMax from 'terra-icon/lib/icon/IconMax';
import IconMaximize from 'terra-icon/lib/icon/IconMaximize';
import IconMediaFastForward from 'terra-icon/lib/icon/IconMediaFastForward';
import IconMediaPause from 'terra-icon/lib/icon/IconMediaPause';
import IconMediaPlay from 'terra-icon/lib/icon/IconMediaPlay';
import IconMediaRecord from 'terra-icon/lib/icon/IconMediaRecord';
import IconMediaRewind from 'terra-icon/lib/icon/IconMediaRewind';
import IconMediaStop from 'terra-icon/lib/icon/IconMediaStop';
import IconMedicationTablet from 'terra-icon/lib/icon/IconMedicationTablet';
import IconMedicationTabletHalf from 'terra-icon/lib/icon/IconMedicationTabletHalf';
import IconMedicationTabletHalfOutline from 'terra-icon/lib/icon/IconMedicationTabletHalfOutline';
import IconMedicationTabletOutline from 'terra-icon/lib/icon/IconMedicationTabletOutline';
import IconMenu from 'terra-icon/lib/icon/IconMenu';
import IconMerge from 'terra-icon/lib/icon/IconMerge';
import IconMicrophone from 'terra-icon/lib/icon/IconMicrophone';
import IconMicrophoneDisabled from 'terra-icon/lib/icon/IconMicrophoneDisabled';
import IconMin from 'terra-icon/lib/icon/IconMin';
import IconMinimize from 'terra-icon/lib/icon/IconMinimize';
import IconMinus from 'terra-icon/lib/icon/IconMinus';
import IconMissedCall from 'terra-icon/lib/icon/IconMissedCall';
import IconModerate from 'terra-icon/lib/icon/IconModerate';
import IconModerateLowLight from 'terra-icon/lib/icon/IconModerateLowLight';
import IconModified from 'terra-icon/lib/icon/IconModified';

import IconNext from 'terra-icon/lib/icon/IconNext';
import IconNoResults from 'terra-icon/lib/icon/IconNoResults';
import IconNoRisk from 'terra-icon/lib/icon/IconNoRisk';
import IconNoRiskLowLight from 'terra-icon/lib/icon/IconNoRiskLowLight';
import IconNoSignal from 'terra-icon/lib/icon/IconNoSignal';
import IconNotification from 'terra-icon/lib/icon/IconNotification';
import IconNotificationDisabled from 'terra-icon/lib/icon/IconNotificationDisabled';
import IconNotificationOff from 'terra-icon/lib/icon/IconNotificationOff';
import IconNotMet from 'terra-icon/lib/icon/IconNotMet';

import IconOutgoingCall from 'terra-icon/lib/icon/IconOutgoingCall';
import IconOutOfNetwork from 'terra-icon/lib/icon/IconOutOfNetwork';
import IconOverDue from 'terra-icon/lib/icon/IconOverDue';
import IconOverDueLowLight from 'terra-icon/lib/icon/IconOverDueLowLight';

import IconPadlock from 'terra-icon/lib/icon/IconPadlock';
import IconPager from 'terra-icon/lib/icon/IconPager';
import IconPanelLeft from 'terra-icon/lib/icon/IconPanelLeft';
import IconPanelRight from 'terra-icon/lib/icon/IconPanelRight';
import IconPaperFolded from 'terra-icon/lib/icon/IconPaperFolded';
import IconPaperPencil from 'terra-icon/lib/icon/IconPaperPencil';
import IconPartiallyMet from 'terra-icon/lib/icon/IconPartiallyMet';
import IconPatientSearch from 'terra-icon/lib/icon/IconPatientSearch';
import IconPause from 'terra-icon/lib/icon/IconPause';
import IconPending from 'terra-icon/lib/icon/IconPending';
import IconPerson from 'terra-icon/lib/icon/IconPerson';
import IconPersonConnection from 'terra-icon/lib/icon/IconPersonConnection';
import IconPersonDoor from 'terra-icon/lib/icon/IconPersonDoor';
import IconPersonHospital from 'terra-icon/lib/icon/IconPersonHospital';
import IconPersonnelPerson from 'terra-icon/lib/icon/IconPersonnelPerson';
import IconPharmacyReject from 'terra-icon/lib/icon/IconPharmacyReject';
import IconPharmacyRejectLowLight from 'terra-icon/lib/icon/IconPharmacyRejectLowLight';
import IconPharmacyReview from 'terra-icon/lib/icon/IconPharmacyReview';
import IconPharmacyVerification from 'terra-icon/lib/icon/IconPharmacyVerification';
import IconPhone from 'terra-icon/lib/icon/IconPhone';
import IconPhoneDown from 'terra-icon/lib/icon/IconPhoneDown';
import IconPill from 'terra-icon/lib/icon/IconPill';
import IconPinDiagonal from 'terra-icon/lib/icon/IconPinDiagonal';
import IconPinDown from 'terra-icon/lib/icon/IconPinDown';
import IconPlusSymbol from 'terra-icon/lib/icon/IconPlusSymbol';
import IconPlusSymbolLight from 'terra-icon/lib/icon/IconPlusSymbolLight';
import IconPrevious from 'terra-icon/lib/icon/IconPrevious';
import IconPrinter from 'terra-icon/lib/icon/IconPrinter';
import IconProjects from 'terra-icon/lib/icon/IconProjects';
import IconProtocol from 'terra-icon/lib/icon/IconProtocol';
import IconProvider from 'terra-icon/lib/icon/IconProvider';

import IconQuestion from 'terra-icon/lib/icon/IconQuestion';
import IconQuestionOutline from 'terra-icon/lib/icon/IconQuestionOutline';

import IconRectangleSymbol from 'terra-icon/lib/icon/IconRectangleSymbol';
import IconRectangleSymbolLight from 'terra-icon/lib/icon/IconRectangleSymbolLight';
import IconRecurringEvent from 'terra-icon/lib/icon/IconRecurringEvent';
import IconRedo from 'terra-icon/lib/icon/IconRedo';
import IconRefresh from 'terra-icon/lib/icon/IconRefresh';
import IconRefusedSlot from 'terra-icon/lib/icon/IconRefusedSlot';
import IconReload from 'terra-icon/lib/icon/IconReload';
import IconReply from 'terra-icon/lib/icon/IconReply';
import IconReplyAll from 'terra-icon/lib/icon/IconReplyAll';
import IconRequired from 'terra-icon/lib/icon/IconRequired';
import IconRight from 'terra-icon/lib/icon/IconRight';
import IconRollup from 'terra-icon/lib/icon/IconRollup';
import IconRotateLeft from 'terra-icon/lib/icon/IconRotateLeft';
import IconRotateRight from 'terra-icon/lib/icon/IconRotateRight';

import IconSave from 'terra-icon/lib/icon/IconSave';
import IconScheduled from 'terra-icon/lib/icon/IconScheduled';
import IconScheduledLowLight from 'terra-icon/lib/icon/IconScheduledLowLight';
import IconScratchPad from 'terra-icon/lib/icon/IconScratchPad';
import IconSearch from 'terra-icon/lib/icon/IconSearch';
import IconSecondaryProvider from 'terra-icon/lib/icon/IconSecondaryProvider';
import IconSend from 'terra-icon/lib/icon/IconSend';
import IconSeparate from 'terra-icon/lib/icon/IconSeparate';
import IconSettings from 'terra-icon/lib/icon/IconSettings';
import IconSharedSchedules from 'terra-icon/lib/icon/IconSharedSchedules';
import IconSimulation from 'terra-icon/lib/icon/IconSimulation';
import IconSortAscending from 'terra-icon/lib/icon/IconSortAscending';
import IconSortDescending from 'terra-icon/lib/icon/IconSortDescending';
import IconSpinner from 'terra-icon/lib/icon/IconSpinner';
import IconSquareSymbol from 'terra-icon/lib/icon/IconSquareSymbol';
import IconSquareSymbolLight from 'terra-icon/lib/icon/IconSquareSymbolLight';
import IconStartPresenting from 'terra-icon/lib/icon/IconStartPresenting';
import IconStatusPositive from 'terra-icon/lib/icon/IconStatusPositive';
import IconStatusPositiveLowLight from 'terra-icon/lib/icon/IconStatusPositiveLowLight';
import IconStatusPositiveWhite from 'terra-icon/lib/icon/IconStatusPositiveWhite';
import IconStatusPositiveWhiteLowLight from 'terra-icon/lib/icon/IconStatusPositiveWhiteLowLight';
import IconStopPresenting from 'terra-icon/lib/icon/IconStopPresenting';
import IconSuccess from 'terra-icon/lib/icon/IconSuccess';
import IconSuccessLowLight from 'terra-icon/lib/icon/IconSuccessLowLight';
import IconSuccessInverse from 'terra-icon/lib/icon/IconSuccessInverse';
import IconSuccessInverseLowLight from 'terra-icon/lib/icon/IconSuccessInverseLowLight';
import IconSwap from 'terra-icon/lib/icon/IconSwap';

import IconTable from 'terra-icon/lib/icon/IconTable';
import IconTag from 'terra-icon/lib/icon/IconTag';
import IconTeardropSymbol from 'terra-icon/lib/icon/IconTeardropSymbol';
import IconTeardropSymbolLight from 'terra-icon/lib/icon/IconTeardropSymbolLight';
import IconTeardropUpSymbol from 'terra-icon/lib/icon/IconTeardropUpSymbol';
import IconTeardropUpSymbolLight from 'terra-icon/lib/icon/IconTeardropUpSymbolLight';
import IconThinDiamondSymbol from 'terra-icon/lib/icon/IconThinDiamondSymbol';
import IconThinDiamondSymbolLight from 'terra-icon/lib/icon/IconThinDiamondSymbolLight';
import IconTile from 'terra-icon/lib/icon/IconTile';
import IconTrash from 'terra-icon/lib/icon/IconTrash';
import IconTreemap from 'terra-icon/lib/icon/IconTreemap';
import IconTrendingDown from 'terra-icon/lib/icon/IconTrendingDown';
import IconTrendingUp from 'terra-icon/lib/icon/IconTrendingUp';
import IconTriangleDownSymbol from 'terra-icon/lib/icon/IconTriangleDownSymbol';
import IconTriangleDownSymbolLight from 'terra-icon/lib/icon/IconTriangleDownSymbolLight';
import IconTriangleSymbol from 'terra-icon/lib/icon/IconTriangleSymbol';
import IconTriangleSymbolLight from 'terra-icon/lib/icon/IconTriangleSymbolLight';
import IconTrophy from 'terra-icon/lib/icon/IconTrophy';

import IconUnavailable from 'terra-icon/lib/icon/IconUnavailable';
import IconUndo from 'terra-icon/lib/icon/IconUndo';
import IconUnexpected from 'terra-icon/lib/icon/IconUnexpected';
import IconUnexpectedLowLight from 'terra-icon/lib/icon/IconUnexpectedLowLight';
import IconUnknown from 'terra-icon/lib/icon/IconUnknown';
import IconUnlock from 'terra-icon/lib/icon/IconUnlock';
import IconUnread from 'terra-icon/lib/icon/IconUnread';
import IconUnspecified from 'terra-icon/lib/icon/IconUnspecified';
import IconUp from 'terra-icon/lib/icon/IconUp';
import IconUpload from 'terra-icon/lib/icon/IconUpload';
import IconUsers from 'terra-icon/lib/icon/IconUsers';

import IconVideoCamera from 'terra-icon/lib/icon/IconVideoCamera';
import IconVideoCameraDisabled from 'terra-icon/lib/icon/IconVideoCameraDisabled';
import IconVisualization from 'terra-icon/lib/icon/IconVisualization';
import IconVolumeSetDecrease from 'terra-icon/lib/icon/IconVolumeSetDecrease';
import IconVolumeSetDefault from 'terra-icon/lib/icon/IconVolumeSetDefault';
import IconVolumeSetIncrease from 'terra-icon/lib/icon/IconVolumeSetIncrease';
import IconVolumeSetMute from 'terra-icon/lib/icon/IconVolumeSetMute';

import IconWarning from 'terra-icon/lib/icon/IconWarning';
import IconWarningLowLight from 'terra-icon/lib/icon/IconWarningLowLight';
import IconWaveform from 'terra-icon/lib/icon/IconWaveform';
import IconWifi from 'terra-icon/lib/icon/IconWifi';
import IconWifiSlash from 'terra-icon/lib/icon/IconWifiSlash';

import IconXSymbol from 'terra-icon/lib/icon/IconXSymbol';
import IconXSymbolLight from 'terra-icon/lib/icon/IconXSymbolLight';

import IconZoomIn from 'terra-icon/lib/icon/IconZoomIn';
import IconZoomOut from 'terra-icon/lib/icon/IconZoomOut';


const TerraIcon = {};

TerraIcon.IconAbnormal = IconAbnormal;
TerraIcon.IconAbnormalLowLight = IconAbnormalLowLight;
TerraIcon.IconAdd = IconAdd;
TerraIcon.IconAddPerson = IconAddPerson;
TerraIcon.IconAlert = IconAlert;
TerraIcon.IconAlertLowLight = IconAlertLowLight;
TerraIcon.IconAllergy = IconAllergy;
TerraIcon.IconAnalytics = IconAnalytics;
TerraIcon.IconAnnouncement = IconAnnouncement;
TerraIcon.IconArchive = IconArchive;
TerraIcon.IconAttachment = IconAttachment;
TerraIcon.IconAudio = IconAudio;
TerraIcon.IconAutoText = IconAutoText;
TerraIcon.IconAvailable = IconAvailable;
TerraIcon.IconAway = IconAway;

TerraIcon.IconBedAssigned = IconBedAssigned;
TerraIcon.IconBedAssignedLowLight = IconBedAssignedLowLight;
TerraIcon.IconBedRequested = IconBedRequested;
TerraIcon.IconBluetooth = IconBluetooth;
TerraIcon.IconBluetoothSlash = IconBluetoothSlash;
TerraIcon.IconBookmark = IconBookmark;
TerraIcon.IconBriefcase = IconBriefcase;
TerraIcon.IconBrokenImage = IconBrokenImage;
TerraIcon.IconBrokenLinkUnlink = IconBrokenLinkUnlink;
TerraIcon.IconBusy = IconBusy;

TerraIcon.IconCalculator = IconCalculator;
TerraIcon.IconCalendar = IconCalendar;
TerraIcon.IconCamera = IconCamera;
TerraIcon.IconCancel = IconCancel;
TerraIcon.IconCaretDown = IconCaretDown;
TerraIcon.IconCaretLeft = IconCaretLeft;
TerraIcon.IconCaretRight = IconCaretRight;
TerraIcon.IconCaretUp = IconCaretUp;
TerraIcon.IconCatalogueNumber = IconCatalogueNumber;
TerraIcon.IconCaution = IconCaution;
TerraIcon.IconCeMarking = IconCeMarking;
TerraIcon.IconChecklist = IconChecklist;
TerraIcon.IconCheckmark = IconCheckmark;
TerraIcon.IconChevron = IconChevron;
TerraIcon.IconChevronDown = IconChevronDown;
TerraIcon.IconChevronLeft = IconChevronLeft;
TerraIcon.IconChevronRight = IconChevronRight;
TerraIcon.IconChevronUp = IconChevronUp;
TerraIcon.IconCircleLinesSymbol = IconCircleLinesSymbol;
TerraIcon.IconCircleSymbol = IconCircleSymbol;
TerraIcon.IconCircleSymbolLight = IconCircleSymbolLight;
TerraIcon.IconClear = IconClear;
TerraIcon.IconClipboard = IconClipboard;
TerraIcon.IconClock = IconClock;
TerraIcon.IconClose = IconClose;
TerraIcon.IconCollapseRow = IconCollapseRow;
TerraIcon.IconComment = IconComment;
TerraIcon.IconCommit = IconCommit;
TerraIcon.IconComplete = IconComplete;
TerraIcon.IconCompose = IconCompose;
TerraIcon.IconConfidential = IconConfidential;
TerraIcon.IconConsultInstructionsForUse = IconConsultInstructionsForUse;
TerraIcon.IconCritical = IconCritical;
TerraIcon.IconCriticalLowLight = IconCriticalLowLight;
TerraIcon.IconCriticalInverse = IconCriticalInverse;
TerraIcon.IconCriticalInverseLowLight = IconCriticalInverseLowLight;

TerraIcon.IconDateOfManufacture = IconDateOfManufacture;
TerraIcon.IconDevice = IconDevice;
TerraIcon.IconDeviceAlert = IconDeviceAlert;
TerraIcon.IconDeviceAlertLowLight = IconDeviceAlertLowLight;
TerraIcon.IconDeviceCheck = IconDeviceCheck;
TerraIcon.IconDeviceCheckLowLight = IconDeviceCheckLowLight;
TerraIcon.IconDiamond = IconDiamond;
TerraIcon.IconDiamondLowLight = IconDiamondLowLight;
TerraIcon.IconDiamondSymbol = IconDiamondSymbol;
TerraIcon.IconDiamondSymbolLight = IconDiamondSymbolLight;
TerraIcon.IconDischargeComingDue = IconDischargeComingDue;
TerraIcon.IconDischargeComingDueLowLight = IconDischargeComingDueLowLight;
TerraIcon.IconDischargeComplete = IconDischargeComplete;
TerraIcon.IconDischargeCompleteLowLight = IconDischargeCompleteLowLight;
TerraIcon.IconDischargeOverDue = IconDischargeOverDue;
TerraIcon.IconDischargeOverDueLowLight = IconDischargeOverDueLowLight;
TerraIcon.IconDocumentPlus = IconDocumentPlus;
TerraIcon.IconDocuments = IconDocuments;
TerraIcon.IconDoNotDisturb = IconDoNotDisturb;
TerraIcon.IconDoorOpen = IconDoorOpen;
TerraIcon.IconDoubleChevronLeft = IconDoubleChevronLeft;
TerraIcon.IconDoubleChevronRight = IconDoubleChevronRight;
TerraIcon.IconDown = IconDown;
TerraIcon.IconDownload = IconDownload;
TerraIcon.IconDrugDrug = IconDrugDrug;
TerraIcon.IconDrugDrugLowLight = IconDrugDrugLowLight;
TerraIcon.IconDue = IconDue;
TerraIcon.IconDueSoon = IconDueSoon;
TerraIcon.IconDueSoonLowLight = IconDueSoonLowLight;

TerraIcon.IconEcRep = IconEcRep;
TerraIcon.IconEdit = IconEdit;
TerraIcon.IconEllipses = IconEllipses;
TerraIcon.IconEnvelope = IconEnvelope;
TerraIcon.IconEnvelopeFill = IconEnvelopeFill;
TerraIcon.IconError = IconError;
TerraIcon.IconErrorLowLight = IconErrorLowLight;
TerraIcon.IconErrorDark = IconErrorDark;
TerraIcon.IconExclamation = IconExclamation;
TerraIcon.IconExpandLess = IconExpandLess;
TerraIcon.IconExpandMore = IconExpandMore;
TerraIcon.IconExpandRow = IconExpandRow;
TerraIcon.IconExtensions = IconExtensions;
TerraIcon.IconExternalLink = IconExternalLink;

TerraIcon.IconFeatured = IconFeatured;
TerraIcon.IconFeaturedOff = IconFeaturedOff;
TerraIcon.IconFeaturedOutline = IconFeaturedOutline;
TerraIcon.IconFeaturedOutlineYellow = IconFeaturedOutlineYellow;
TerraIcon.IconFirst = IconFirst;
TerraIcon.IconFitHeight = IconFitHeight;
TerraIcon.IconFitScale = IconFitScale;
TerraIcon.IconFitWidth = IconFitWidth;
TerraIcon.IconFlag = IconFlag;
TerraIcon.IconFlipHorizontal = IconFlipHorizontal;
TerraIcon.IconFlipVertical = IconFlipVertical;
TerraIcon.IconFlowsheet = IconFlowsheet;
TerraIcon.IconFolder = IconFolder;
TerraIcon.IconForward = IconForward;
TerraIcon.IconFunnel = IconFunnel;

TerraIcon.IconGapChecking = IconGapChecking;
TerraIcon.IconGlasses = IconGlasses;
TerraIcon.IconGroup = IconGroup;

TerraIcon.IconHalfRating = IconHalfRating;
TerraIcon.IconHazardLow = IconHazardLow;
TerraIcon.IconHelp = IconHelp;
TerraIcon.IconHelpLowLight = IconHelpLowLight;
TerraIcon.IconHelpInverse = IconHelpInverse;
TerraIcon.IconHelpInverseLowLight = IconHelpInverseLowLight;
TerraIcon.IconHide = IconHide;
TerraIcon.IconHigh = IconHigh;
TerraIcon.IconHighLowLight = IconHighLowLight;
TerraIcon.IconHighInverse = IconHighInverse;
TerraIcon.IconHighInverseLowLight = IconHighInverseLowLight;
TerraIcon.IconHighPriority = IconHighPriority;
TerraIcon.IconHold = IconHold;
TerraIcon.IconHospital = IconHospital;
TerraIcon.IconHouse = IconHouse;

TerraIcon.IconImage = IconImage;
TerraIcon.IconImplant = IconImplant;
TerraIcon.IconIncomingCall = IconIncomingCall;
TerraIcon.IconIncomplete = IconIncomplete;
TerraIcon.IconIncompleteInverse = IconIncompleteInverse;
TerraIcon.IconIncompleteInverseLowLight = IconIncompleteInverseLowLight;
TerraIcon.IconInformation = IconInformation;
TerraIcon.IconInformationLowLight = IconInformationLowLight;
TerraIcon.IconInformationInverse = IconInformationInverse;
TerraIcon.IconInformationInverseLowLight = IconInformationInverseLowLight;
TerraIcon.IconIPass = IconIPass;
TerraIcon.IconItalicI = IconItalicI;

TerraIcon.IconKeyboard = IconKeyboard;
TerraIcon.IconKnurling = IconKnurling;

TerraIcon.IconLast = IconLast;
TerraIcon.IconLeft = IconLeft;
TerraIcon.IconLeftPane = IconLeftPane;
TerraIcon.IconLightbulb = IconLightbulb;
TerraIcon.IconLink = IconLink;
TerraIcon.IconList = IconList;
TerraIcon.IconLocationPin = IconLocationPin;
TerraIcon.IconLookback = IconLookback;
TerraIcon.IconLow = IconLow;
TerraIcon.IconLowLowLight = IconLowLowLight;
TerraIcon.IconLowRisk = IconLowRisk;
TerraIcon.IconLowRiskLowLight = IconLowRiskLowLight;

TerraIcon.IconManufacturer = IconManufacturer;
TerraIcon.IconMax = IconMax;
TerraIcon.IconMaximize = IconMaximize;
TerraIcon.IconMediaFastForward = IconMediaFastForward;
TerraIcon.IconMediaPause = IconMediaPause;
TerraIcon.IconMediaPlay = IconMediaPlay;
TerraIcon.IconMediaRecord = IconMediaRecord;
TerraIcon.IconMediaRewind = IconMediaRewind;
TerraIcon.IconMediaStop = IconMediaStop;
TerraIcon.IconMedicationTablet = IconMedicationTablet;
TerraIcon.IconMedicationTabletHalf = IconMedicationTabletHalf;
TerraIcon.IconMedicationTabletHalfOutline = IconMedicationTabletHalfOutline;
TerraIcon.IconMedicationTabletOutline = IconMedicationTabletOutline;
TerraIcon.IconMenu = IconMenu;
TerraIcon.IconMerge = IconMerge;
TerraIcon.IconMicrophone = IconMicrophone;
TerraIcon.IconMicrophoneDisabled = IconMicrophoneDisabled;
TerraIcon.IconMin = IconMin;
TerraIcon.IconMinimize = IconMinimize;
TerraIcon.IconMinus = IconMinus;
TerraIcon.IconMissedCall = IconMissedCall;
TerraIcon.IconModerate = IconModerate;
TerraIcon.IconModerateLowLight = IconModerateLowLight;
TerraIcon.IconModified = IconModified;

TerraIcon.IconNext = IconNext;
TerraIcon.IconNoResults = IconNoResults;
TerraIcon.IconNoRisk = IconNoRisk;
TerraIcon.IconNoRiskLowLight = IconNoRiskLowLight;
TerraIcon.IconNoSignal = IconNoSignal;
TerraIcon.IconNotification = IconNotification;
TerraIcon.IconNotificationDisabled = IconNotificationDisabled;
TerraIcon.IconNotificationOff = IconNotificationOff;
TerraIcon.IconNotMet = IconNotMet;

TerraIcon.IconOutgoingCall = IconOutgoingCall;
TerraIcon.IconOutOfNetwork = IconOutOfNetwork;
TerraIcon.IconOverDue = IconOverDue;
TerraIcon.IconOverDueLowLight = IconOverDueLowLight;

TerraIcon.IconPadlock = IconPadlock;
TerraIcon.IconPager = IconPager;
TerraIcon.IconPanelLeft = IconPanelLeft;
TerraIcon.IconPanelRight = IconPanelRight;
TerraIcon.IconPaperFolded = IconPaperFolded;
TerraIcon.IconPaperPencil = IconPaperPencil;
TerraIcon.IconPartiallyMet = IconPartiallyMet;
TerraIcon.IconPatientSearch = IconPatientSearch;
TerraIcon.IconPause = IconPause;
TerraIcon.IconPending = IconPending;
TerraIcon.IconPerson = IconPerson;
TerraIcon.IconPersonConnection = IconPersonConnection;
TerraIcon.IconPersonDoor = IconPersonDoor;
TerraIcon.IconPersonHospital = IconPersonHospital;
TerraIcon.IconPersonnelPerson = IconPersonnelPerson;
TerraIcon.IconPharmacyReject = IconPharmacyReject;
TerraIcon.IconPharmacyRejectLowLight = IconPharmacyRejectLowLight;
TerraIcon.IconPharmacyReview = IconPharmacyReview;
TerraIcon.IconPharmacyVerification = IconPharmacyVerification;
TerraIcon.IconPhone = IconPhone;
TerraIcon.IconPhoneDown = IconPhoneDown;
TerraIcon.IconPill = IconPill;
TerraIcon.IconPinDiagonal = IconPinDiagonal;
TerraIcon.IconPinDown = IconPinDown;
TerraIcon.IconPlusSymbol = IconPlusSymbol;
TerraIcon.IconPlusSymbolLight = IconPlusSymbolLight;
TerraIcon.IconPrevious = IconPrevious;
TerraIcon.IconPrinter = IconPrinter;
TerraIcon.IconProjects = IconProjects;
TerraIcon.IconProtocol = IconProtocol;
TerraIcon.IconProvider = IconProvider;

TerraIcon.IconQuestion = IconQuestion;
TerraIcon.IconQuestionOutline = IconQuestionOutline;

TerraIcon.IconRectangleSymbol = IconRectangleSymbol;
TerraIcon.IconRectangleSymbolLight = IconRectangleSymbolLight;
TerraIcon.IconRecurringEvent = IconRecurringEvent;
TerraIcon.IconRedo = IconRedo;
TerraIcon.IconRefresh = IconRefresh;
TerraIcon.IconRefusedSlot = IconRefusedSlot;
TerraIcon.IconReload = IconReload;
TerraIcon.IconReply = IconReply;
TerraIcon.IconReplyAll = IconReplyAll;
TerraIcon.IconRequired = IconRequired;
TerraIcon.IconRight = IconRight;
TerraIcon.IconRollup = IconRollup;
TerraIcon.IconRotateLeft = IconRotateLeft;
TerraIcon.IconRotateRight = IconRotateRight;

TerraIcon.IconSave = IconSave;
TerraIcon.IconScheduled = IconScheduled;
TerraIcon.IconScheduledLowLight = IconScheduledLowLight;
TerraIcon.IconScratchPad = IconScratchPad;
TerraIcon.IconSearch = IconSearch;
TerraIcon.IconSecondaryProvider = IconSecondaryProvider;
TerraIcon.IconSend = IconSend;
TerraIcon.IconSeparate = IconSeparate;
TerraIcon.IconSettings = IconSettings;
TerraIcon.IconSharedSchedules = IconSharedSchedules;
TerraIcon.IconSimulation = IconSimulation;
TerraIcon.IconSortAscending = IconSortAscending;
TerraIcon.IconSortDescending = IconSortDescending;
TerraIcon.IconSpinner = IconSpinner;
TerraIcon.IconSquareSymbol = IconSquareSymbol;
TerraIcon.IconSquareSymbolLight = IconSquareSymbolLight;
TerraIcon.IconStartPresenting = IconStartPresenting;
TerraIcon.IconStatusPositive = IconStatusPositive;
TerraIcon.IconStatusPositiveLowLight = IconStatusPositiveLowLight;
TerraIcon.IconStatusPositiveWhite = IconStatusPositiveWhite;
TerraIcon.IconStatusPositiveWhiteLowLight = IconStatusPositiveWhiteLowLight;
TerraIcon.IconStopPresenting = IconStopPresenting;
TerraIcon.IconSuccess = IconSuccess;
TerraIcon.IconSuccessLowLight = IconSuccessLowLight;
TerraIcon.IconSuccessInverse = IconSuccessInverse;
TerraIcon.IconSuccessInverseLowLight = IconSuccessInverseLowLight;
TerraIcon.IconSwap = IconSwap;

TerraIcon.IconTable = IconTable;
TerraIcon.IconTag = IconTag;
TerraIcon.IconTeardropSymbol = IconTeardropSymbol;
TerraIcon.IconTeardropSymbolLight = IconTeardropSymbolLight;
TerraIcon.IconTeardropUpSymbol = IconTeardropUpSymbol;
TerraIcon.IconTeardropUpSymbolLight = IconTeardropUpSymbolLight;
TerraIcon.IconThinDiamondSymbol = IconThinDiamondSymbol;
TerraIcon.IconThinDiamondSymbolLight = IconThinDiamondSymbolLight;
TerraIcon.IconTile = IconTile;
TerraIcon.IconTrash = IconTrash;
TerraIcon.IconTreemap = IconTreemap;
TerraIcon.IconTrendingDown = IconTrendingDown;
TerraIcon.IconTrendingUp = IconTrendingUp;
TerraIcon.IconTriangleDownSymbol = IconTriangleDownSymbol;
TerraIcon.IconTriangleDownSymbolLight = IconTriangleDownSymbolLight;
TerraIcon.IconTriangleSymbol = IconTriangleSymbol;
TerraIcon.IconTriangleSymbolLight = IconTriangleSymbolLight;
TerraIcon.IconTrophy = IconTrophy;

TerraIcon.IconUnavailable = IconUnavailable;
TerraIcon.IconUndo = IconUndo;
TerraIcon.IconUnexpected = IconUnexpected;
TerraIcon.IconUnexpectedLowLight = IconUnexpectedLowLight;
TerraIcon.IconUnknown = IconUnknown;
TerraIcon.IconUnlock = IconUnlock;
TerraIcon.IconUnread = IconUnread;
TerraIcon.IconUnspecified = IconUnspecified;
TerraIcon.IconUp = IconUp;
TerraIcon.IconUpload = IconUpload;
TerraIcon.IconUsers = IconUsers;

TerraIcon.IconVideoCamera = IconVideoCamera;
TerraIcon.IconVideoCameraDisabled = IconVideoCameraDisabled;
TerraIcon.IconVisualization = IconVisualization;
TerraIcon.IconVolumeSetDecrease = IconVolumeSetDecrease;
TerraIcon.IconVolumeSetDefault = IconVolumeSetDefault;
TerraIcon.IconVolumeSetIncrease = IconVolumeSetIncrease;
TerraIcon.IconVolumeSetMute = IconVolumeSetMute;

TerraIcon.IconWarning = IconWarning;
TerraIcon.IconWarningLowLight = IconWarningLowLight;
TerraIcon.IconWaveform = IconWaveform;
TerraIcon.IconWifi = IconWifi;
TerraIcon.IconWifiSlash = IconWifiSlash;

TerraIcon.IconXSymbol = IconXSymbol;
TerraIcon.IconXSymbolLight = IconXSymbolLight;

TerraIcon.IconZoomIn = IconZoomIn;
TerraIcon.IconZoomOut = IconZoomOut;

export default TerraIcon;
